version: "3.8"

services:
  app:
    container_name: docker-react-c
    image: docker-react-i
    build:
      context: .
    ports:
      - 8082:80
    volumes:
      - /react_modules:/app # Mount the current working directory into /app in the container
